services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/minidoodle
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      - minidoodle-network
  db:
    image: postgres:17.6-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=minidoodle
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - minidoodle-network

networks:
  minidoodle-network:
    driver: bridge

volumes:
  postgres_data:
